using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Jumping : MonoBehaviour
{
 public float jumpHeight = 7f;
 public bool isGrounded;
 
 private Rigidbody rb;
 
 void Start()
 {
  rb = GetComponent<Rigidbody>();
 }
 
 void Update()
 {
    if (isGrounded)
    {
       if (Input.GetButtonDown("Jump"))
       {
       rb.AddForce(Vector3.up * jumpHeight);
       }
    }
 }
 
 void OnCollisionEnter(Collision other)
 {
     if (other.gameObject.tag == "Ground")
     {
         isGrounded = true;
     }
 }
 
 void OnCollisionExit(Collision other)
 {
     if (other.gameObject.tag == "Ground")
     {
         isGrounded = false;
     }

}
}